//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// FireGuardCamera.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TESTDLG_DIALOG              102
#define IDR_HTML_DEVICEINFODLG          103
#define IDR_HTML_EVENTSCHEDULEINFODLG   104
#define IDR_HTML_EVENTTRIGGERINFODLG    105
#define IDR_HTML_MOTIONINFODLG          106
#define IDR_HTML_NETWORKIPADDRINFODLG   107
#define IDR_HTML_NETWORKIPFILTERINFODLG 108
#define IDR_HTML_NOTIFYMAILINGINFODLG   109
#define IDR_HTML_OVERLAYTEXTINFODLG     110
#define IDR_HTML_PRIVACYMASKINFODLG     111
#define IDR_HTML_TIMEINFODLG            112
#define IDR_HTML_USERINFODLG            113
#define IDR_HTML_VIDEOINFODLG           114
#define IDR_HTML_FEATUREINFODLG         115
#define IDR_HTML_STREAMINFODLG          116
#define IDR_HTML_CUSTOMTRIGGERINFODLG   117
#define IDR_HTML_CUSTOMSTROBEINFODLG    118
#define IDR_MAINFRAME                   128
#define IDD_WAIT                        129
#define IDD_EVENT_SCHEDULE_INFO         130
#define IDD_STREAM_INFO                 131
#define IDD_STREAMING                   134
#define IDD_CUSTOM_CTRL                 135
#define IDD_DIGITAL_IO_INFO             136
#define IDD_THERMAL_TEMPERATURE_INFO    137
#define IDD_DLG_DETAIL                  138
#define IDD_NETWORK_IPADDR_INFO         148
#define IDD_USER_INFO                   149
#define IDD_MOTION_INFO                 153
#define IDD_EVENT_TRIGGER_INFO          157
#define IDD_TIME_INFO                   159
#define IDD_NETWORK_IPFILTER_INFO       161
#define IDC_LIST_USER                   235
#define IDC_BUTTON_DELETE               236
#define IDC_BUTTON_DELETE_NOTIFY        237
#define IDC_COMBO_INBOUND_COMPRESSION_TYPE 253
#define IDC_COMBO_PARITY_TYPE           256
#define IDC_COMBO_STOP_BITS             257
#define IDC_COMBO_CODEC_TYPE            261
#define IDC_COMBO_SCAN_TYPE             262
#define IDC_COMBO_QUALITY_CONTROL       263
#define IDC_COMBO_EXPOSURE_MODE         266
#define IDC_COMBO_DIRECTION_SENSITIVITY 275
#define IDC_BUTTON_DISCOVERY            1000
#define IDC_BUTTON_ADD_CAMERA           1001
#define IDC_LIST_CAMERA                 1002
#define IDC_EDIT_CAMERA_INFO            1003
#define IDD_FEATURE_INFO                1003
#define IDC_STATIC_DOT                  1004
#define IDC_COMBO_ENABLE_VIDEO          1005
#define IDC_BUTTON_DEVICE               1006
#define IDC_BUTTON_FEATURE              1007
#define IDC_BUTTON_MOTION               1008
#define IDD_SERIAL_INFO                 1008
#define IDC_BUTTON_NTP_DELETE           1009
#define IDC_BUTTON_OVERLAY_TEXT         1009
#define IDC_LIST_STREAM                 1009
#define IDC_CHECK_ZEROCONF              1010
#define IDC_BUTTON_NTP_MODIFY           1010
#define IDC_BUTTON_PRIVACY_MASK         1010
#define IDC_EDIT_NAME                   1011
#define IDC_BUTTON_TIME_MODIFY          1011
#define IDC_BUTTON_STREAM               1011
#define IDC_BUTTON_TIME                 1012
#define IDC_IPADDRESS1                  1013
#define IDC_BUTTON_USER                 1013
#define IDC_SUBNET_MASK                 1014
#define IDC_COMBO_EVENT_TYPE            1014
#define IDC_EDIT_PORT                   1014
#define IDD_CUSTOM_TRIGGER_INFO         1014
#define IDC_BUTTON_NETWORK_IPADDRESS    1014
#define IDC_GATEWAY                     1015
#define IDC_COMBO_NOTIFY_METHOD         1015
#define IDC_COMBO_PERMISSION            1015
#define IDC_CHECK_ENABLE_MOTION         1015
#define IDD_CUSTOM_STROBE_INFO          1015
#define IDC_BUTTON_STREAM_ROI_INFO      1015
#define IDC_PRIMARY_DNS                 1016
#define IDC_BUTTON_NETWORK_IP_FILTER    1016
#define IDC_BUTTON_APPLY                1017
#define IDC_BUTTON_NOTIFY_MAILING       1017
#define IDC_BUTTON_MODIFY_TRIGGER       1018
#define IDC_IPADDRESS_START_RANGE       1018
#define IDC_BUTTON_EVENT_TRIGGER        1018
#define IDC_LIST_OVERLAY                1019
#define IDC_BUTTON_MODIFY_PARAM         1019
#define IDC_IPADDRESS_END_RANGE         1019
#define IDC_CHECK_ENABLE_MASK           1019
#define IDC_BUTTON_EVENT_SCHEDULE       1019
#define IDC_BUTTON_ADD                  1020
#define IDC_BUTTON_CUSTOM_TRIGGER       1020
#define IDC_BUTTON_MODIFY_MOTION        1020
#define IDC_BUTTON_ADD_NOTIFY           1021
#define IDC_BUTTON_MODIFY               1021
#define IDC_BUTTON_CUSTOM_STROBE        1021
#define IDC_BUTTON_MODIFY_REGION        1021
#define IDC_CHECK1                      1021
#define IDC_CHECK_GAMMA                 1021
#define IDC_CHECK_CLR_INVERT            1021
#define IDC_IPADDRESS_MASK              1022
#define IDC_BUTTON_MODIFY_NOTIFICATION  1022
#define IDC_BUTTON_STORAGE              1022
#define IDC_BUTTON_MODIFY2              1022
#define IDC_COMBO_POWER_FREQUENCY       1023
#define IDC_MULTICAST_IPADDRESS         1023
#define IDC_BUTTON_MODIFY_IPFILTER      1023
#define IDC_BUTTON_CUSTOM_STORAGE       1023
#define IDC_CHECK2                      1023
#define IDC_CHECK_SHOW_TEMP             1023
#define IDC_COMBO_WB_MODE               1024
#define IDC_BUTTON_CUSTOM_CTRL          1024
#define IDC_CHECK3                      1024
#define IDC_CHECK_SHOW_CLR_BAR          1024
#define IDC_EDIT_WB_LEVEL               1025
#define IDC_RADIO_MASK                  1025
#define IDD_PRIVACY_MASK_INFO           1025
#define IDC_BUTTON_STREAMING            1025
#define IDC_CHECK4                      1025
#define IDC_CHECK_SHOW_CENTER           1025
#define IDC_SLIDER_BRIGHTNESS           1026
#define IDC_RADIO_RANGE                 1026
#define IDC_BUTTON_REBOOT               1026
#define IDC_CHECK_SHOW_INDICATOR        1026
#define IDC_SLIDER_HUE                  1027
#define IDC_BUTTON_EXPORT               1027
#define IDC_SLIDER_CONTRAST             1028
#define IDC_BUTTON_IMPORT               1028
#define IDD_DEVICE_INFO                 1029
#define IDC_SLIDER_SHARPNESS            1029
#define IDC_COMBO_AUTOCLIP_MODE         1029
#define IDC_BUTTON_THERMAL_SPOT         1029
#define IDC_EDIT_EXPOSURE_TARGET        1030
#define IDC_EDIT_NIGHTCLIP_VALUE        1030
#define IDC_BUTTON_DIGITAL_IO           1030
#define IDC_EDIT_EXPOSURE_MIN           1031
#define IDC_BUTTON_AUTOCLIP_MODIFY      1031
#define IDC_BUTTON_DDNS                 1031
#define IDC_EDIT_EXPOSURE_MAX           1032
#define IDC_BUTTON_SNAPSHOT             1032
#define IDC_SLIDER_GAIN                 1033
#define IDC_BUTTON_SERIALPORT           1033
#define IDC_EDIT_COMMAND                1033
#define IDC_COMBO_MAX_VALUE             1033
#define IDC_BUTTON_SEND                 1034
#define IDC_BUTTON_AUTOCLIP_MODIFY2     1034
#define IDC_BUTTON_SENSOR_UP_MODIFY     1034
#define IDC_BUTTON_CHANNEL_SNAPSHOT     1034
#define IDC_EDIT_ADDRESS                1035
#define IDC_BUTTON_CHANNEL_MODIFY       1035
#define IDC_BUTTON_SNMP                 1035
#define IDC_COMBO_PROTOCOL              1036
#define IDC_BUTTON_CHANNEL_SYNC         1036
#define IDC_BUTTON_PPPOE                1036
#define IDC_EDIT_WRITE                  1037
#define IDC_COMBO_VIDEO_OUT_TYPE        1037
#define IDC_BUTTON_LOG_CLEAR            1037
#define IDC_BUTTON_WRITE                1038
#define IDC_BUTTON_VIDEO_OUT_MODIFY     1038
#define IDC_BUTTON_DEL_CAMERA           1038
#define IDC_BUTTON_READ                 1039
#define IDC_COMBO_RECORD_TYPE           1039
#define IDC_BUTTON_DEL_CAMERA2          1039
#define IDC_BUTTON_CHANGE_IP            1039
#define IDC_SLIDER_GAMMA                1040
#define IDC_EDIT_READ                   1040
#define IDC_BUTTON_DEFOG_MODIFY         1040
#define IDC_COMBO_DAYNIGHT_TYPE         1041
#define IDC_BUTTON_AGC_MODIFY           1041
#define IDC_CHECK_DAYNIGHT_SCHEDULE     1042
#define IDC_BUTTON_CONNECT              1042
#define IDC_BUTTON_RECORD_MODIFY        1042
#define IDC_EDIT_BEGIN_HOUR             1043
#define IDD_NOTIFY_MAILING_INFO         1043
#define IDC_BUTTON_DISCONNECT           1043
#define IDC_COMBO_STROBE_STRENGTH       1043
#define IDC_COMBO_CH_SNAPSHOT           1044
#define IDC_BUTTON_STROBE_NIGHT_MODIFY  1044
#define IDC_RADIO_GRID                  1045
#define IDC_COMBO_ENABLE_1              1045
#define IDC_BUTTON_STROBE_STRENGTH_MODIFY 1045
#define IDC_EDIT_END_HOUR               1046
#define IDC_RADIO_ROI                   1046
#define IDC_COMBO_ENABLE_2              1046
#define IDC_COMBO_ENABLE_3              1047
#define IDC_EDIT_START_X_1              1048
#define IDC_COMBO_ENABLE_11             1048
#define IDC_COMBO_ALARM_ENABLE_1        1048
#define IDC_EDIT_START_X_2              1049
#define IDC_COMBO_ENABLE_12             1049
#define IDC_COMBO_ALARM_ENABLE_2        1049
#define IDC_EDIT_START_X_3              1050
#define IDC_COMBO_ENABLE_13             1050
#define IDC_COMBO_ALARM_ENABLE_3        1050
#define IDC_EDIT_START_Y_1              1051
#define IDC_COMBO_ENABLE_21             1051
#define IDC_COMBO_ALARM_MODE_1          1051
#define IDC_EDIT_POSITION_X             1052
#define IDC_EDIT_START_Y_2              1052
#define IDC_COMBO_ENABLE_22             1052
#define IDC_COMBO_ALARM_MODE_2          1052
#define IDC_EDIT_POSITION_Y             1053
#define IDC_EDIT_START_Y_3              1053
#define IDC_COMBO_ENABLE_23             1053
#define IDC_COMBO_ALARM_MODE_3          1053
#define IDC_EDIT_CONSTANT_BITRATE       1054
#define IDC_COMBO_ENABLE_4              1054
#define IDC_EDIT_FIXED_QUALITY          1055
#define IDC_EDIT_X_4                    1055
#define IDC_EDIT_VBR_UPPER              1056
#define IDC_EDIT_Y_4                    1056
#define IDC_EDIT_VBR_LOWER              1057
#define IDC_COMBO_ENABLE_5              1057
#define IDC_COMBO_ENABLE                1058
#define IDC_EDIT_X_5                    1058
#define IDC_COMBO_MIRROR_ENABLE         1059
#define IDC_EDIT_Y_5                    1059
#define IDC_COMBO_VIDEO_OUT_ENABLE      1059
#define IDC_SLIDER_SATURATION           1060
#define IDC_COMBO_SNAPSHOT_TYPE         1060
#define IDC_BUTTON_MODIFY1              1060
#define IDC_COMBO_DEFOG_TYPE            1060
#define IDC_EDIT_WIDTH                  1061
#define IDC_BUTTON_MODIFY3              1061
#define IDC_COMBO_AGC_TYPE              1061
#define IDC_COMBO_ENABLE_AUDIO          1062
#define IDC_BUTTON_REFRESH              1062
#define IDC_BUTTON_MODIFY4              1062
#define IDC_COMBO_RECORD_ENABLE         1062
#define IDC_EDIT_MAX                    1063
#define IDC_EDIT_BITMASK                1063
#define IDC_EDIT_HEIGHT                 1063
#define IDC_EDIT_CHANNEL_CNT            1063
#define IDC_BUTTON_MODIFY5              1063
#define IDC_EDIT_START_IPADDRESS_V6_RANGE 1064
#define IDC_EDIT_BITRATE                1064
#define IDC_COMBO_CHANNEL               1064
#define IDC_COMBO_ENABLE_6              1064
#define IDC_EDIT_DURATION               1065
#define IDC_EDIT_END_IPADDRESS_V6_RANGE 1065
#define IDC_EDIT_Y2                     1065
#define IDC_EDIT_SAMPLING_RATE          1065
#define IDC_BUTTON_GET                  1065
#define IDC_COMBO_STROBE_NIGHT_ENABLE   1065
#define IDC_EDIT_MACADDRESS             1066
#define IDC_EDIT_SECONDARY_DNS_V6       1066
#define IDC_EDIT_ROW                    1066
#define IDC_EDIT_Y3                     1066
#define IDC_EDIT_AUDIO_RESOLUTION       1066
#define IDC_EDIT_MIN_TEMPERATURE        1066
#define IDC_EDIT_FIRMWAREVERSION        1067
#define IDC_EDIT_COLUMN                 1067
#define IDC_EDIT_Y4                     1067
#define IDC_EDIT_AUDIO_SOURCE_PORT      1067
#define IDC_EDIT_MAX_TEMPERATURE        1067
#define IDC_EDIT_MIN_HOR_RESOLUTION     1068
#define IDC_EDIT_RTSP_PORT              1068
#define IDC_EDIT_CENTER_TEMPERATURE     1068
#define IDC_EDIT_MIN_VER_RESOLUTION     1069
#define IDC_EDIT_HTTP_PORT              1069
#define IDC_EDIT_MIN_COOR               1069
#define IDC_EDIT_SENSITIVITY            1070
#define IDC_EDIT_USER_TRIGGER_THRESHOLD 1070
#define IDC_EDIT_MAX_COOR               1070
#define IDC_EDIT_MOTION_Y3              1071
#define IDC_EDIT_AUDIO_INBOUND_PORT     1071
#define IDC_EDIT_AVR_TEMPERATURE        1071
#define IDC_EDIT_MOTION_Y4              1072
#define IDC_EDIT_TEMPERATURE_1          1072
#define IDC_COMBO_RESOLUTION_SIZE       1072
#define IDC_EDIT_KEY_FRAME_INTERVAL     1073
#define IDC_EDIT_TEMPERATURE_2          1073
#define IDC_EDIT_TEMPERATURE_3          1074
#define IDC_EDIT_MAX_PACKET_SIZE        1075
#define IDC_EDIT_TEMPERATURE_4          1075
#define IDC_EDIT_AUDIO_PAKCET_LENGTH    1076
#define IDC_EDIT_TEMPERATURE_5          1076
#define IDC_EDIT_HUE                    1077
#define IDC_EDIT_VIDEO_SOURCE_PORT      1077
#define IDC_EDIT_X_6                    1077
#define IDC_CHECK_RTSP                  1078
#define IDC_EDIT_Y_6                    1078
#define IDC_EDIT_SHARPNESS              1079
#define IDC_CHECK_HTTP                  1079
#define IDC_EDIT_TEMPERATURE_6          1079
#define IDC_EDIT_SATURATION             1080
#define IDC_RADIO_UNICAST               1080
#define IDC_BUTTON_MODIFY6              1080
#define IDC_EDIT_GAIN                   1081
#define IDC_RADIO_UNICAST_UDP           1081
#define IDC_COMBO_ENABLE_7              1081
#define IDC_EDIT_GAMMA                  1082
#define IDC_RADIO_UNICAST_TCP           1082
#define IDC_EDIT_X_7                    1082
#define IDC_RADIO_MULTICAST             1083
#define IDC_EDIT_Y_7                    1083
#define IDC_EDIT_VIDEO_DEST_PORT        1084
#define IDC_EDIT_TEMPERATURE_7          1084
#define IDC_EDIT_AUDIO_DEST_PORT        1085
#define IDC_BUTTON_MODIFY7              1085
#define IDC_EDIT_DEST_IPADDR            1086
#define IDC_COMBO_ENABLE_8              1086
#define IDC_EDIT_TTL                    1087
#define IDC_EDIT_X_8                    1087
#define IDC_CHECK_SECURE_RTP            1088
#define IDC_EDIT_Y_8                    1088
#define IDC_EDIT_AUDIO_INBOUND_PAKCET_LENGTH 1089
#define IDC_EDIT_TEMPERATURE_8          1089
#define IDC_BUTTON_MODIFY8              1090
#define IDC_COMBO_ENABLE_9              1091
#define IDC_EDIT_X_9                    1092
#define IDC_EDIT_Y_9                    1093
#define IDC_EDIT_TEMPERATURE_9          1094
#define IDC_BUTTON_MODIFY9              1095
#define IDC_COMBO_ENABLE_10             1096
#define IDC_EDIT_X_10                   1097
#define IDC_EDIT_Y_10                   1098
#define IDC_EDIT_TEMPERATURE_10         1099
#define IDC_BUTTON_MODIFY10             1100
#define IDC_EDIT_X_1                    1101
#define IDC_EDIT_X_2                    1102
#define IDC_EDIT_X_3                    1103
#define IDC_EDIT_Y_1                    1104
#define IDC_EDIT_Y_2                    1105
#define IDC_EDIT_Y_3                    1106
#define IDC_LIST_INPUT                  1107
#define IDC_EDIT_TEMPERATURE_11         1107
#define IDC_COMBO_ALARM_DELAY_1         1107
#define IDC_COMBO_ALARM_START_DELAY_1   1107
#define IDC_EDIT_INPUT_ID               1108
#define IDC_EDIT_TEMPERATURE_12         1108
#define IDC_COMBO_ALARM_DELAY_2         1108
#define IDC_COMBO_ALARM_START_DELAY_2   1108
#define IDC_COMBO_INPUT_ENABLE          1109
#define IDC_EDIT_PWD                    1109
#define IDC_EDIT_TEMPERATURE_13         1109
#define IDC_COMBO_ALARM_DELAY_3         1109
#define IDC_COMBO_ALARM_START_DELAY_3   1109
#define IDC_COMBO_INPUT_ACTIVE          1110
#define IDC_EDIT_TEMPERATURE_14         1110
#define IDC_COMBO_ALARM_DELAY_4         1110
#define IDC_COMBO_ALARM_START_DELAY_4   1110
#define IDC_LIST_OUTPUT                 1111
#define IDC_EDIT_TEMPERATURE_15         1111
#define IDC_COMBO_ALARM_DELAY_5         1111
#define IDC_COMBO_ALARM_START_DELAY_5   1111
#define IDC_EDIT_OUTPUT_ID              1112
#define IDC_EDIT_TEMPERATURE_16         1112
#define IDC_COMBO_ALARM_DELAY_6         1112
#define IDC_COMBO_ALARM_START_DELAY_6   1112
#define IDC_COMBO_OUTPUT_ENABLE         1113
#define IDC_EDIT_TEMPERATURE_17         1113
#define IDC_COMBO_ALARM_DELAY_7         1113
#define IDC_COMBO_ALARM_START_DELAY_7   1113
#define IDC_COMBO_OUTPUT_ACTIVE         1114
#define IDC_EDIT_TEMPERATURE_18         1114
#define IDC_COMBO_ALARM_DELAY_8         1114
#define IDC_COMBO_ALARM_START_DELAY_8   1114
#define IDC_BUTTON_INPUT_MODIFY         1115
#define IDC_EDIT_TEMPERATURE_19         1115
#define IDC_COMBO_ALARM_DELAY_9         1115
#define IDC_COMBO_ALARM_START_DELAY_9   1115
#define IDC_BUTTON_OUTPUT_MODIFY        1116
#define IDC_EDIT_TEMPERATURE_20         1116
#define IDC_COMBO_ALARM_DELAY_0         1116
#define IDC_COMBO_ALARM_START_DELAY_0   1116
#define IDC_EDIT_OUTPUT_DURATION        1117
#define IDC_COMBO_ALARM_STOP_DELAY_1    1117
#define IDC_EDIT_I_FRAME_INTERVAL       1118
#define IDC_COMBO_OUTPUT_TOGGLE_ENABLE  1118
#define IDC_COMBO_ALARM_STOP_DELAY_2    1118
#define IDC_EDIT_PARAM                  1119
#define IDC_BUTTON_RESOLUTION_SIZE_CHANGE 1119
#define IDC_EDIT_OUTPUT_TOGGLE_INTERVAL 1119
#define IDC_COMBO_ALARM_STOP_DELAY_3    1119
#define IDC_COMBO_POLARITY              1120
#define IDC_BUTTON_I_FRAME_ITV_CHANGE   1120
#define IDC_COMBO_SNMP_ENABLE           1120
#define IDC_EDIT_OUTPUT_TOGGLE_ID       1120
#define IDC_COMBO_ALARM_STOP_DELAY_4    1120
#define IDC_COMBO_SOURCE                1121
#define IDC_COMBO_STROBE_MODE           1121
#define IDC_COMBO_CST_ENABLE            1121
#define IDC_EDIT_OUTPUT_MAX_DURATION    1121
#define IDC_COMBO_ALARM_STOP_DELAY_5    1121
#define IDC_LIST_PARAM                  1122
#define IDC_IPADDRESS_CST               1122
#define IDC_BUTTON_OUTPUT_EXECUTE       1122
#define IDC_COMBO_ALARM_STOP_DELAY_6    1122
#define IDC_EDIT_PARAM_ID               1123
#define IDC_COMBO_ALARM_STOP_DELAY_7    1123
#define IDC_COMBO_NETWORK_ID            1124
#define IDC_EDIT_PARAM_GAIN             1124
#define IDC_COMBO_SVC_NAME              1124
#define IDC_COMBO_ALARM_STOP_DELAY_8    1124
#define IDC_COMBO_IP_VERSION            1125
#define IDC_EDIT_PARAM_SHUTTER          1125
#define IDC_EDIT_HOST_NAME              1125
#define IDC_COMBO_ALARM_DELAY_18        1125
#define IDC_COMBO_ALARM_STOP_DELAY_9    1125
#define IDC_COMBO_IP_ADDRESS_TYPE       1126
#define IDC_EDIT_PARAM_INCREMENT        1126
#define IDC_BUTTON_OUTPUT_TOGGLE_SET    1126
#define IDC_EDIT_WIDTH_0                1126
#define IDC_COMBO_CAPTURE_FILE_SAVING   1127
#define IDC_EDIT_THERMAL_VER            1127
#define IDC_COMBO_ALARM_STOP_DELAY_0    1127
#define IDC_COMBO_CAPTURE_FORMAT        1128
#define IDC_EDIT_HASH_CODE              1128
#define IDC_COMBO_PALETTE               1128
#define IDC_COMBO_TABLE_ONOFF           1129
#define IDC_EDIT_PERIOD                 1129
#define IDC_RADIO_GAIN_MANUAL           1129
#define IDC_RADIO_GAIN_AUTO             1130
#define IDC_EDIT_IPV6_BITMASK           1131
#define IDC_EDIT_GAIN_MIN               1131
#define IDC_CHECK_UPNP                  1132
#define IDC_EDIT_GAIN_MAX               1132
#define IDC_CHECK_MULTI_CAST            1133
#define IDC_EDIT_BRIGHTNESS             1133
#define IDC_EDIT_MULTICAST_PORT         1134
#define IDC_COMBO_TEMP_MODE             1134
#define IDC_EDIT_MULTICAST_TTL          1135
#define IDC_COMBO_NRF                   1135
#define IDC_EDIT_IPADDRESS_V6           1136
#define IDC_COMBO_NUC_TIME              1136
#define IDC_MULTICAST_IPADDRESS_V6      1137
#define IDC_COMBO_NUC_AUTO              1137
#define IDC_COMBO_ENABLE_14             1137
#define IDC_COMBO_ALARM_ENABLE_4        1137
#define IDC_EDIT_GATEWAY_V6             1138
#define IDC_COMBO_EDGE_ENHANCE          1138
#define IDC_COMBO_ENABLE_15             1138
#define IDC_COMBO_ALARM_ENABLE_5        1138
#define IDC_EDIT_PRIMARY_DNS_V6         1139
#define IDC_COMBO_ENABLE_16             1139
#define IDC_COMBO_ALARM_ENABLE_6        1139
#define IDC_COMBO_TIME_MODE             1140
#define IDC_COMBO_ENABLE_17             1140
#define IDC_COMBO_ALARM_ENABLE_7        1140
#define IDC_EDIT_LOCAL_TIME             1141
#define IDC_COMBO_ENABLE_18             1141
#define IDC_COMBO_ALARM_ENABLE_8        1141
#define IDC_EDIT_TIME_ZONE              1142
#define IDC_COMBO_ENABLE_19             1142
#define IDC_COMBO_ALARM_ENABLE_9        1142
#define IDC_LIST_NTP_SERVER             1143
#define IDC_COMBO_ENABLE_20             1143
#define IDC_COMBO_ALARM_ENABLE_0        1143
#define IDC_COMBO_FORMAT_TYPE           1144
#define IDC_COMBO_ENABLE_24             1144
#define IDC_COMBO_ALARM_MODE_4          1144
#define IDC_EDIT_NTP_SERVER_ID          1145
#define IDC_COMBO_ENABLE_25             1145
#define IDC_COMBO_ALARM_MODE_5          1145
#define IDC_EDIT_NTP_SERVER_PORT        1146
#define IDC_COMBO_ENABLE_26             1146
#define IDC_COMBO_ALARM_MODE_6          1146
#define IDC_IPADDRESS_NTP_SERVER        1147
#define IDC_COMBO_ENABLE_27             1147
#define IDC_COMBO_ALARM_MODE_7          1147
#define IDC_EDIT_IPADDRESS_V6_NTP_SERVER 1148
#define IDC_COMBO_ENABLE_28             1148
#define IDC_COMBO_ALARM_MODE_8          1148
#define IDC_EDIT_NTP_SERVER_HOST_NAME   1149
#define IDC_COMBO_ENABLE_29             1149
#define IDC_COMBO_ALARM_MODE_9          1149
#define IDC_EDIT_MAX_FRAME_RATE         1150
#define IDC_COMBO_ENABLE_30             1150
#define IDC_COMBO_ALARM_MODE_0          1150
#define IDC_COMBO_ENABLE_31             1151
#define IDC_COMBO_ALARM_CONDITION_1     1151
#define IDC_EDIT_SERIAL_PORT_ID         1152
#define IDC_COMBO_ENABLE_32             1152
#define IDC_COMBO_ALARM_CONDITION_2     1152
#define IDC_COMBO_PORT_TYPE             1153
#define IDC_COMBO_ENABLE_33             1153
#define IDC_COMBO_ALARM_CONDITION_3     1153
#define IDC_COMBO_DUPLEX_MODE           1154
#define IDC_COMBO_ENABLE_34             1154
#define IDC_COMBO_ALARM_CONDITION_4     1154
#define IDC_COMBO_DIRECTION             1155
#define IDC_COMBO_ENABLE_35             1155
#define IDC_COMBO_ALARM_CONDITION_5     1155
#define IDC_EDIT_BAUD_RATE              1156
#define IDC_COMBO_ENABLE_36             1156
#define IDC_COMBO_ALARM_CONDITION_6     1156
#define IDC_EDIT_DATA_BITS              1157
#define IDC_COMBO_ENABLE_37             1157
#define IDC_COMBO_ALARM_CONDITION_7     1157
#define IDC_COMBO_ENABLE_38             1158
#define IDC_COMBO_ALARM_CONDITION_8     1158
#define IDC_COMBO_ENABLE_39             1159
#define IDC_COMBO_ALARM_CONDITION_9     1159
#define IDC_COMBO_ENABLE_40             1160
#define IDC_COMBO_ALARM_CONDITION_0     1160
#define IDC_COMBO_ENABLE_41             1161
#define IDC_COMBO_ENABLE_ENTIRE         1161
#define IDC_EDIT_X_11                   1162
#define IDC_EDIT_X_ENTIRE               1162
#define IDC_EDIT_ID                     1163
#define IDC_EDIT_Y_31                   1163
#define IDC_EDIT_Y_ENTIRE               1163
#define IDC_EDIT_USER_NAME              1164
#define IDC_EDIT_VIDEO_INPUT_CHANNEL_ID 1164
#define IDC_EDIT_TEMPERATURE_21         1164
#define IDC_COMBO_ALARM_TEMP_ENTIRE     1164
#define IDC_SECOND_DNS                  1165
#define IDC_EDIT_PASSWORD               1165
#define IDC_BUTTON_MODIFY11             1165
#define IDC_BUTTON_MODIFYENTIRE         1165
#define IDC_EDIT_TEMPERATURE_22         1166
#define IDC_COMBO_ALARM_DELAY_ENTIRE    1166
#define IDC_COMBO_ALARM_START_DELAY_ENTIRE 1166
#define IDC_BUTTON_NTP_ADD              1167
#define IDC_EDIT_Y_32                   1167
#define IDC_EDIT_WIDTH_ENTIRE           1167
#define IDC_EDIT_Y_33                   1168
#define IDC_EDIT_HEIGHT_ENTIRE          1168
#define IDC_COMBO_ENABLE_42             1169
#define IDC_COMBO_ALARM_ENABLE_ENTIRE   1169
#define IDC_COMBO_ENABLE_43             1170
#define IDC_COMBO_ALARM_MODE_ENTIRE     1170
#define IDC_COMBO_ENABLE_44             1171
#define IDC_COMBO_ALARM_CONDITION_ENTIRE 1171
#define IDC_EDIT_INPUT_PORT             1172
#define IDC_COMBO_ALARM_STOP_DELAY_ENTIRE 1172
#define IDC_EDIT_UNICAST_INTERFACE_ID   1173
#define IDC_COMBO_ONOFF                 1197
#define IDC_EDIT_DELAY                  1198
#define IDC_EDIT_MODE                   1199
#define IDC_EDIT_NOISE_FILTER           1202
#define IDC_LIST_STROBE                 1202
#define IDC_COMBO_STROBE                1203
#define IDC_EDIT_PERIODIC_INTERVAL      1203
#define IDC_EDIT_MIN                    1204
#define IDC_EDIT_X2                     1206
#define IDC_EDIT_X3                     1207
#define IDC_BUTTON_SET_TRIGGER          1208
#define IDC_EDIT_X4                     1208
#define IDC_EDIT_EVENT_INTERVAL         1218
#define IDC_EDIT_IOINPUTID              1220
#define IDC_EDIT_IOOUTPUTID             1221
#define IDC_EDIT_NOTIFY_INTERVAL        1222
#define IDC_TREE_TRIGGER                1223
#define IDC_RADIO_BEGIN                 1224
#define IDC_RADIO_BEGIN_END             1225
#define IDC_RADIO_RECURRING             1226
#define IDC_EDIT_EVENT_DESC             1227
#define IDC_COMBO_RESOLUTION            1230
#define IDC_STATIC_W                    1231
#define IDC_STATIC_H                    1232
#define IDC_EDIT_BEGIN_DATE             1240
#define IDC_EDIT_END_DATE               1241
#define IDC_COMBO_FRAME_RATE            1254
#define IDC_STATIC_IPV4                 1266
#define IDC_STATIC_IPV6                 1267
#define IDC_STATIC_IPV4_ADDRESS         1268
#define IDC_STATIC_IPV4_SUBNET_MASK     1269
#define IDC_STATIC_IPV4_GATEWAY         1270
#define IDC_STATIC_IPV4_PRIMARY_DNS     1271
#define IDC_STATIC_IPV4_SECONDARY_DNS   1272
#define IDC_STATIC_IPV6_ADDRESS         1273
#define IDC_STATIC_IPV6_BITMASK         1274
#define IDC_STATIC_IPV6_GATEWAY         1275
#define IDC_STATIC_IPV6_PRIMARY_DNS     1276
#define IDC_STATIC_IPV6_SECONDARY_DNS   1277
#define IDC_LIST_IPFILTER               1282
#define IDD_OVERLAY_TEXT_INFO           1283
#define IDD_STREAM_ROI_INFO             1284
#define IDC_BUTTON_ADD_OVERLAY          1285
#define IDD_THERMAL_SPOT_INFO           1285
#define IDC_BUTTON_DELETE_OVERLAY       1286
#define IDD_DYNAMIC_DNS_INFO            1286
#define IDC_EDIT_OVERLAY_ID             1287
#define IDD_SNMP_INFO                   1287
#define IDC_BUTTON_MODIFY_OVERLAY       1288
#define IDD_PPPOE_INFO                  1288
#define IDD_THERMAL_CTRL_INFO           1289
#define IDC_BUTTON_ADD_REGION           1290
#define IDD_THERMAL_CORRECTION_INFO     1290
#define IDC_BUTTON_DELETE_REGION        1291
#define IDD_THERMAL_REGION_INFO         1291
#define IDC_CHECK_OVERLAY_ENABLE        1302
#define IDC_CHECK_TIMESTAMP_ENABLE      1303
#define IDC_EDIT_DATETIME_FORMAT        1304
#define IDC_EDIT_BACK_COLOR             1305
#define IDC_EDIT_FONT_COLOR             1306
#define IDC_EDIT_FONT_SIZE              1307
#define IDC_EDIT_DISPLAY_TEXT           1308
#define IDC_RADIO_HORIZENTAL_LEFT       1309
#define IDC_RADIO_HORIZENTAL_RIGHT      1310
#define IDC_RADIO_HORIZENTAL_CENTER     1311
#define IDC_RADIO_VERTICAL_TOP          1312
#define IDC_RADIO_VERTICAL_BOTTOM       1313
#define IDC_BUTTON_BACK_COLORDLG        1314
#define IDC_BUTTON_FONT_COLORDLG        1315
#define IDC_COMBO_ROTATION              1316
#define IDC_EDIT_MODEL                  1321
#define IDC_EDIT_SERIALNUMBER           1322
#define IDC_CHECK_ENABLE_PRIVACY        1323
#define IDC_CHECK_ENABLE_REGION         1324
#define IDC_EDIT_SAMPLING_INTERVAL      1325
#define IDC_EDIT_START_TRIGGER_TIME     1326
#define IDC_EDIT_END_TRIGGER_TIME       1327
#define IDC_EDIT_MIN_PIXEL              1328
#define IDC_EDIT_MAX_PIXEL              1329
#define IDC_EDIT_THRESHOLD              1330
#define IDC_CHECK_ENABLE                1331
#define IDC_EDIT_IPADDRESS_V6_MASK      1332
#define IDC_COMBO_ADDRESS_PERMISSION    1333
#define IDC_EDIT_X1                     1334
#define IDC_EDIT_Y1                     1335
#define IDC_EDIT_IPADDRESS_V4           1356
#define IDC_COMBO_ADDRESS_FORMAT        1364
#define IDC_EDIT_HOSTNAME               1366
#define IDC_LIST_MAIL                   1374
#define IDC_EDIT_SENDER_ADDRESS         1375
#define IDC_EDIT_RECVER_ADDRESS         1376
#define IDC_EDIT_SUBJECT                1377
#define IDC_CHECK_ENABLE_VIDEO_URL      1378
#define IDC_CHECK_ENABLE_SNAPSHOT       1379
#define IDC_CHECK_ENABLE_VIDEO_CLIP     1380
#define IDC_COMBO_AUTH_MODE             1381
#define IDC_COMBO_POP_ADDRESS_FORMAT    1382
#define IDC_EDIT_POP_HOSTNAME           1383
#define IDC_EDIT_POP_IPADDRESS_V4       1384
#define IDC_EDIT_POP_IPADDRESS_V6       1385
#define IDC_EDIT_ACCOUNT_NAME           1386
#define IDC_BUTTON_APPLY_IPADDRESS      1503
#define IDC_BUTTON_APPLY_DISCOVERY      1504
#define IDC_EDIT_INPUT_CHANNEL_ID       1511
#define IDC_COMBO_AUDIO_COMPRESSION_TYPE 1512
#define IDC_COMBO_MOTION_ID             1515
#define IDC_EDIT_MOTION_X1              1516
#define IDC_EDIT_MOTION_Y1              1517
#define IDC_EDIT_MOTION_X2              1518
#define IDC_EDIT_MOTION_Y2              1519
#define IDC_EDIT_MOTION_X3              1520
#define IDC_EDIT_MOTION_X4              1521
#define IDC_COMBO_PRIVACY_ID            1522
#define IDC_STATIC_RESOLUTION           1523
#define IDC_BUTTON_MODIFY_SCHEDULE      1524
#define IDC_BUTTON_MODIFY_NOTIFY        1525
#define IDC_CHECK_BUSSINESS_SCHEDULE    1526
#define IDC_CHECK_WEEKEND_SCHEDULE      1527
#define IDC_CHECK_ALL_SCHEDULE          1528
#define IDC_BUTTON_MODIFY_ADDRESS       1528
#define IDC_EDIT_CONTRAST               1529
#define IDC_BUTTON_THERMAL_MODIFY       1530
#define IDC_BUTTON_SET_REGION_ALARM     1531
#define IDC_EDIT_EMISSIVITY             1531
#define IDC_BUTTON_THERMAL_CORRECTION   1532
#define IDC_EDIT_TRANSMISSION           1532
#define IDC_COMBO_ENABLE_0              1532
#define IDC_EDIT_ATMOSPHERE             1533
#define IDC_EDIT_X_0                    1533
#define IDC_EDIT_DIST_CORR              1534
#define IDC_EDIT_Y_0                    1534
#define IDC_EDIT_ZERO_OFFSET            1535
#define IDC_EDIT_TEMPERATURE_0          1535
#define IDC_COMBO_ALARM_TEMP_0          1535
#define IDC_EDIT_WIDTH_1                1536
#define IDC_EDIT_WIDTH_2                1537
#define IDC_EDIT_WIDTH_3                1538
#define IDC_EDIT_HEIGHT_1               1539
#define IDC_EDIT_HEIGHT_2               1540
#define IDC_EDIT_HEIGHT_3               1541
#define IDC_EDIT_WIDTH_4                1545
#define IDC_EDIT_WIDTH_5                1546
#define IDC_EDIT_WIDTH_6                1547
#define IDC_EDIT_WIDTH_7                1548
#define IDC_EDIT_WIDTH_8                1549
#define IDC_EDIT_WIDTH_9                1550
#define IDC_EDIT_HEIGHT_4               1555
#define IDC_EDIT_HEIGHT_5               1556
#define IDC_EDIT_HEIGHT_6               1557
#define IDC_EDIT_HEIGHT_7               1558
#define IDC_EDIT_HEIGHT_8               1559
#define IDC_EDIT_HEIGHT_9               1560
#define IDC_EDIT_HEIGHT_0               1561
#define IDC_COMBO_ALARM_TEMP_1          1562
#define IDC_COMBO_ALARM_TEMP_2          1563
#define IDC_COMBO_ALARM_TEMP_3          1564
#define IDC_COMBO_ALARM_TEMP_4          1565
#define IDC_COMBO_ALARM_TEMP_5          1566
#define IDC_COMBO_ALARM_TEMP_6          1567
#define IDC_COMBO_ALARM_TEMP_7          1568
#define IDC_COMBO_ALARM_TEMP_8          1569
#define IDC_COMBO_ALARM_TEMP_9          1570
#define IDC_BUTTON_MODIFY0              1571
#define IDC_BUTTON_GET_REGION_ALARM     1572
#define IDC_EDIT_TEMP_CENTER_ENTIRE     1573
#define IDC_EDIT_TEMP_MIN_ENTIRE        1574
#define IDC_EDIT_TEMP_MAX_ENTIRE        1575
#define IDC_EDIT_TEMP_AVG_ENTIRE        1576
#define IDC_EDIT_MIN_X_ENTIRE           1577
#define IDC_EDIT_MIN_Y_ENTIRE           1578
#define IDC_EDIT_MAX_X_ENTIRE           1579
#define IDC_EDIT_MAX_Y_ENTIRE           1580
#define IDC_EDIT_TEMP_CENTER_0          1581
#define IDC_EDIT_TEMP_MIN_0             1582
#define IDC_EDIT_TEMP_MAX_0             1583
#define IDC_EDIT_TEMP_AVG_0             1584
#define IDC_EDIT_MIN_X_0                1585
#define IDC_EDIT_MIN_Y_0                1586
#define IDC_EDIT_MAX_X_0                1587
#define IDC_EDIT_MAX_Y_0                1588
#define IDC_EDIT_TEMP_CENTER_1          1589
#define IDC_EDIT_TEMP_MIN_1             1590
#define IDC_EDIT_TEMP_MAX_1             1591
#define IDC_EDIT_TEMP_AVG_1             1592
#define IDC_EDIT_MIN_X_1                1593
#define IDC_EDIT_MIN_Y_1                1594
#define IDC_EDIT_MAX_X_1                1595
#define IDC_EDIT_MAX_Y_1                1596
#define IDC_EDIT_TEMP_CENTER_2          1597
#define IDC_EDIT_TEMP_MIN_2             1598
#define IDC_EDIT_TEMP_MAX_2             1599
#define IDC_EDIT_TEMP_AVG_2             1600
#define IDC_EDIT_MIN_X_2                1601
#define IDC_EDIT_MIN_Y_2                1602
#define IDC_EDIT_MAX_X_2                1603
#define IDC_EDIT_MAX_Y_2                1604
#define IDC_EDIT_TEMP_CENTER_3          1605
#define IDC_EDIT_TEMP_MIN_3             1606
#define IDC_EDIT_TEMP_MAX_3             1607
#define IDC_EDIT_TEMP_AVG_3             1608
#define IDC_EDIT_MIN_X_3                1609
#define IDC_EDIT_MIN_Y_3                1610
#define IDC_EDIT_MAX_X_3                1611
#define IDC_EDIT_MAX_Y_3                1612
#define IDC_EDIT_TEMP_CENTER_4          1613
#define IDC_EDIT_TEMP_MIN_4             1614
#define IDC_EDIT_TEMP_MAX_4             1615
#define IDC_EDIT_TEMP_AVG_4             1616
#define IDC_EDIT_MIN_X_4                1617
#define IDC_EDIT_MIN_Y_4                1618
#define IDC_EDIT_MAX_X_4                1619
#define IDC_EDIT_MAX_Y_4                1620
#define IDC_EDIT_TEMP_CENTER_5          1621
#define IDC_EDIT_TEMP_MIN_5             1622
#define IDC_EDIT_TEMP_MAX_5             1623
#define IDC_EDIT_TEMP_AVG_5             1624
#define IDC_EDIT_MIN_X_5                1625
#define IDC_EDIT_MIN_Y_5                1626
#define IDC_EDIT_MAX_X_5                1627
#define IDC_EDIT_MAX_Y_5                1628
#define IDC_BUTTON1                     1629
#define IDC_BUTTON_SET_NUC              1630
#define IDC_STATIC_TEMP_VALID_0         1631
#define IDC_STATIC_TEMP_VALID_ENTIRE    1632
#define IDC_STATIC_TEMP_VALID_1         1633
#define IDC_STATIC_TEMP_VALID_2         1634
#define IDC_BT_DUPCHECK                 1634
#define IDC_STATIC_TEMP_VALID_3         1635
#define IDC_IPADDRESS                   1635
#define IDC_STATIC_TEMP_VALID_4         1636
#define IDC_EDIT_TEMP_CENTER_6          1637
#define IDC_EDIT_TEMP_MIN_6             1638
#define IDC_EDIT_TEMP_MAX_6             1639
#define IDC_EDIT_TEMP_AVG_6             1640
#define IDC_EDIT_MIN_X_6                1641
#define IDC_EDIT_MIN_Y_6                1642
#define IDC_EDIT_MAX_X_6                1643
#define IDC_EDIT_MAX_Y_6                1644
#define IDC_EDIT_TEMP_CENTER_7          1645
#define IDC_EDIT_TEMP_MIN_7             1646
#define IDC_EDIT_TEMP_MAX_7             1647
#define IDC_EDIT_TEMP_AVG_7             1648
#define IDC_EDIT_MIN_X_7                1649
#define IDC_EDIT_MIN_Y_7                1650
#define IDC_EDIT_MAX_X_7                1651
#define IDC_EDIT_MAX_Y_7                1652
#define IDC_EDIT_TEMP_CENTER_8          1653
#define IDC_EDIT_TEMP_MIN_8             1654
#define IDC_EDIT_TEMP_MAX_8             1655
#define IDC_EDIT_TEMP_AVG_8             1656
#define IDC_EDIT_MIN_X_8                1657
#define IDC_EDIT_MIN_Y_8                1658
#define IDC_EDIT_MAX_X_8                1659
#define IDC_EDIT_MAX_Y_8                1660
#define IDC_EDIT_TEMP_CENTER_9          1661
#define IDC_EDIT_TEMP_MIN_9             1662
#define IDC_EDIT_TEMP_MAX_9             1663
#define IDC_EDIT_TEMP_AVG_9             1664
#define IDC_EDIT_MIN_X_9                1665
#define IDC_EDIT_MIN_Y_9                1666
#define IDC_EDIT_MAX_X_9                1667
#define IDC_EDIT_MAX_Y_9                1668
#define IDC_STATIC_TEMP_VALID_5         1669
#define IDC_STATIC_TEMP_VALID_6         1670
#define IDC_STATIC_TEMP_VALID_7         1671
#define IDC_STATIC_TEMP_VALID_8         1672
#define IDC_STATIC_TEMP_VALID_9         1673
#define IDC_STATIC_TEMP_ALARM_ENTIRE    1674
#define IDC_STATIC_TEMP_ALARM_0         1675
#define IDC_STATIC_TEMP_ALARM_1         1676
#define IDC_STATIC_TEMP_ALARM_2         1677
#define IDC_STATIC_TEMP_ALARM_3         1678
#define IDC_STATIC_TEMP_ALARM_4         1679
#define IDC_STATIC_TEMP_ALARM_5         1680
#define IDC_STATIC_TEMP_ALARM_6         1681
#define IDC_STATIC_TEMP_ALARM_7         1682
#define IDC_STATIC_TEMP_ALARM_8         1683
#define IDC_STATIC_TEMP_ALARM_9         1684

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1637
#define _APS_NEXT_SYMED_VALUE           119
#endif
#endif
