//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// FireGuardGraph.rc에서 사용되고 있습니다.
//
#define ID_BT_DEL1                      4
#define ID_BT_DEL2                      5
#define ID_BT_DEL3                      6
#define ID_BT_DEL4                      7
#define IDD_REALTIMETRACK_DIALOG        102
#define IDR_MAINFRAME                   128
#define IDI_RunPB                       130
#define IDI_FreezePB                    132
#define IDI_StopPB                      133
#define IDD_DLG_SMS                     134
#define IDD_DLG_SELECT_CAMERA           137
#define IDC_ChartViewer                 1000
#define IDC_VelocityViewer              1001
#define IDC_CHECK_ALARM                 1002
#define IDC_STATIC_NAME1                1003
#define IDC_UpdatePeriod                1004
#define IDC_SlopeViewer                 1005
#define IDC_EDIT_TELNO1                 1005
#define IDC_CHECK_SEND_MSG              1006
#define IDC_EDIT_NAME1                  1007
#define IDC_CHECK_TREND                 1007
#define IDC_STATIC_NAME2                1008
#define IDC_FreezePB                    1009
#define IDC_EDIT_TELNO2                 1009
#define IDC_AlphaValue                  1010
#define IDC_STATIC_NAME3                1010
#define IDC_EDIT_NAME2                  1010
#define IDC_BetaValue                   1011
#define IDC_TEMPER_1                    1011
#define IDC_GammaValue                  1012
#define IDC_TEMPER_3                    1012
#define IDC_EDIT_TELNO3                 1012
#define IDC_RunPB                       1013
#define IDC_EDIT_NAME3                  1013
#define IDC_TEMPER_2                    1014
#define IDC_STATIC_NAME4                1015
#define IDC_EDIT_TELNO4                 1015
#define IDC_TEMPER_4                    1016
#define IDC_EDIT_NAME4                  1016
#define IDC_STATIC_NAME5                1017
#define IDC_TEMPER_5                    1018
#define IDC_STATIC_NAME6                1019
#define IDC_TEMPER_6                    1020
#define IDC_STATIC_NAME7                1021
#define IDC_TEMPER_7                    1022
#define IDC_CHECK_SMS1                  1022
#define IDC_STATIC_NAME8                1023
#define IDC_CHECK_SMS2                  1023
#define IDC_TEMPER_8                    1024
#define IDC_CHECK_SMS3                  1024
#define IDC_CHECK_1                     1025
#define IDC_CHECK_SMS4                  1025
#define IDC_CHECK_2                     1026
#define IDC_CHECK_3                     1027
#define IDC_CHECK_4                     1028
#define IDC_CHECK_5                     1029
#define IDC_CHECK_6                     1030
#define IDC_SHOW_LOG                    1031
#define IDC_EDIT_THRESHOLD_MAX          1032
#define IDC_CHECK_7                     1033
#define IDC_CHECK_8                     1034
#define IDC_BUTTON_MAX_APPLY            1035
#define IDC_EDIT_THRESHOLD_MIN          1036
#define IDC_CHECK_ALL1                  1037
#define IDC_DATETIMEPICKER1             1037
#define IDC_ANIMATE1                    1038
#define IDC_CHECK_DATE                  1038
#define IDC_RADIO1                      1039
#define IDC_SHOW_LOG2                   1039
#define IDC_OPEN_FOLDER                 1039
#define IDC_RADIO2                      1040
#define IDC_OPEN_FOLDER2                1040
#define IDC_BT_STOP                     1040
#define IDC_STATIC_COUNTER              1040
#define IDC_RADIO3                      1041
#define IDC_EDIT_VELOC_MAX              1041
#define IDC_RADIO4                      1042
#define IDC_CHECK_ALL2                  1042
#define IDC_CHECK_VELOCITY              1042
#define IDC_EDIT_VELOC_MAX2             1042
#define IDC_EDIT_LOG_DURATION           1042
#define IDC_RADIO5                      1043
#define IDC_BUTTON_VELOC_APPLY          1043
#define IDC_RADIO6                      1044
#define IDC_BUTTON_SMS_MGR              1044
#define IDC_RADIO7                      1045
#define IDC_VELOC_ANIMATE               1045
#define IDC_RADIO8                      1046
#define IDC_BUTTON_VELOC_APPLY2         1046
#define IDC_BUTTON_LOG_DURATION_APPLY   1046
#define IDC_EDIT_VELOC_RANGE            1047
#define IDC_RADIO9                      1047
#define IDC_EDIT_VELOC_DEVI             1048
#define IDC_RADIO10                     1048
#define IDC_RADIO11                     1049
#define IDC_STATIC_VELO_SEC             1049
#define IDC_BUTTON1                     1050
#define IDC_BT_SHOW_1                   1050
#define IDC_BT_SHOW_2                  1051
#define IDC_BT_SHOW_3                   1052
#define IDC_BT_SHOW_4                   1053
#define IDC_BT_SHOW_5                   1054
#define IDC_BT_SHOW_6                   1055
#define IDC_BT_SHOW_7                   1056
#define IDC_BT_SHOW_8                   1057

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1058
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
